load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "interfacepollution",
    srcs = [
        "bad_example.go",
        "decoupling_example.go",
        "good_example.go",
        "good_example_consumer.go",
        "restricting_example.go",
    ],
    importpath = "github.com/yourusername/go-100-mistakes/book/ch02-code-project-organization/05-interface-pollution",
    visibility = ["//visibility:public"],
)
