load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "variableshadowing",
    srcs = ["shadowing.go"],
    importpath = "github.com/yourusername/100-go-mistakes/book/ch02-code-project-organization/01-variable-shadowing",
    visibility = ["//visibility:public"],
)

go_test(
    name = "variableshadowing_test",
    srcs = ["shadowing_test.go"],
    embed = [":variableshadowing"],
)
